### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [2]:
import numpy as np

#### np.array 함수로 생성하기

In [3]:
x=np.array([1,2,3,4])
print(x)
y=np.array([[2,3,4],[1,2,5]]) #2행 3열
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [8]:
np.ones((4,5)) #tuple로 전달해야함

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.ones((2,3,4)) #3행 4열짜리 2개 -3차원

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.zeros((3,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [12]:
np.empty((3,4))

array([[9.58911079e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.02360867e-306, 1.23229853e+165, 2.57120552e+184,
        3.42165105e-032],
       [4.11444565e+179, 2.51301382e+180, 4.54586677e+174,
        1.95069955e+160]])

In [13]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [14]:
np.eye(5) #5*5행렬에서, 대각선만 1, 나머지 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기

In [15]:
np.linspace(1,10,3) #(시작, 끝, 나누는 개수) 원소간의 차가 동일하게 나눔

array([ 1. ,  5.5, 10. ])

In [16]:
np.linspace(1,10,4) #좌표줄때 사용함 주로

array([ 1.,  4.,  7., 10.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [20]:
x=np.arange(1,16)
print(x)
x.shape

x.reshape(5,3) #5행 3열로바꿔라 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [21]:
x.reshape(5,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])