### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2,3) #2행 3열의 행렬을 random한 수(0과 1사이)로 채움

array([[0.51901339, 0.82994773, 0.27700643],
       [0.92441946, 0.02085435, 0.88987473]])

In [3]:
np.random.rand(4,5,3)

array([[[0.7547341 , 0.58183333, 0.77684354],
        [0.78247387, 0.27671873, 0.62875319],
        [0.6610927 , 0.19734056, 0.95990641],
        [0.76793953, 0.21569409, 0.493048  ],
        [0.67242182, 0.21488719, 0.06411678]],

       [[0.01682501, 0.96144018, 0.06770717],
        [0.06065453, 0.41806361, 0.51500282],
        [0.02048266, 0.1309278 , 0.62293715],
        [0.83116838, 0.92018084, 0.67986427],
        [0.04779733, 0.62126144, 0.04918577]],

       [[0.26095322, 0.14797382, 0.22402045],
        [0.8443063 , 0.67257146, 0.14136287],
        [0.09217242, 0.12358002, 0.27759933],
        [0.10539653, 0.33706692, 0.74318595],
        [0.85492848, 0.66228002, 0.24339658]],

       [[0.96175924, 0.21079073, 0.79788791],
        [0.60055622, 0.77195055, 0.70355161],
        [0.0532903 , 0.30849422, 0.06702795],
        [0.97019868, 0.2186087 , 0.48170824],
        [0.8414124 , 0.71569918, 0.98370962]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(2,3) #정규분포를 따르는 랜덤한 수로

array([[-0.30984537, -0.85046967, -0.52706508],
       [ 0.08205883,  1.29833729, -1.24540505]])

In [6]:
np.random.randn(2,3,4) #3행 4열짜리 2개

array([[[ 0.61087835, -0.48598874, -0.26589398, -0.84753985],
        [-1.35772584,  2.40127246,  0.25478233, -0.84544511],
        [-1.31313305,  1.28216624,  0.12582722, -1.24521738]],

       [[-0.58033516, -0.2947902 , -0.62942338, -0.49251171],
        [ 1.01894817, -1.40570659, -2.19089129,  0.69266019],
        [-0.05726528, -1.70716778,  0.32050736, -0.59340214]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [11]:
np.random.randint(1,100, size=(3,5)) #(low, high=None,size=())

array([[12, 75, 93, 16, 39],
       [61, 15, 23, 13,  6],
       [94, 38, 52, 99, 78]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [22]:
np.random.seed(42)

np.random.randn(2,3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [24]:
np.random.choice(100,size=(3, 4))

array([[ 1, 63, 59, 20],
       [32, 75, 57, 21],
       [88, 48, 90, 58]])

In [26]:
x=np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x,size=(2, 2),replace=False) # replace False이면, 중복 허용 안함

array([[1. , 2. ],
       [2.6, 1.5]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [28]:
np.random.uniform(1.0,3.0,size=(4,5))

array([[1.09290083, 2.2150897 , 1.34104825, 1.13010319, 2.89777107],
       [2.93126407, 2.6167947 , 1.60922754, 1.19534423, 2.36846605],
       [1.88030499, 1.24407647, 1.99035382, 1.06877704, 2.8186408 ],
       [1.51755996, 2.32504457, 1.62342215, 2.04013604, 2.09342056]])

In [31]:
np.random.normal(size=(4,5))
#np.random.randn(3,4)

array([[-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572]])