## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [3]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

#### 연산 함수
 - add, substract, multiply, divide

In [4]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.65233105 0.41345414 0.7603125  0.11067135 0.74959253]
 [0.71625023 0.02045568 0.89715346 0.30766303 0.95675051]
 [0.4971545  0.97621689 0.58681699 0.64892518 0.44117848]]


In [5]:
np.add(x,y) #인덱스가 같은 원소끼리 (shape이 같아야 가능)

array([[ 0.65233105,  1.41345414,  2.7603125 ,  3.11067135,  4.74959253],
       [ 5.71625023,  6.02045568,  7.89715346,  8.30766303,  9.95675051],
       [10.4971545 , 11.97621689, 12.58681699, 13.64892518, 14.44117848]])

In [6]:
np.subtract(x,y)

array([[-0.65233105,  0.58654586,  1.2396875 ,  2.88932865,  3.25040747],
       [ 4.28374977,  5.97954432,  6.10284654,  7.69233697,  8.04324949],
       [ 9.5028455 , 10.02378311, 11.41318301, 12.35107482, 13.55882152]])

In [7]:
x+y

array([[ 0.65233105,  1.41345414,  2.7603125 ,  3.11067135,  4.74959253],
       [ 5.71625023,  6.02045568,  7.89715346,  8.30766303,  9.95675051],
       [10.4971545 , 11.97621689, 12.58681699, 13.64892518, 14.44117848]])

In [8]:
x*y

array([[ 0.        ,  0.41345414,  1.520625  ,  0.33201406,  2.99837013],
       [ 3.58125116,  0.12273411,  6.28007425,  2.46130421,  8.61075457],
       [ 4.971545  , 10.73838583,  7.04180387,  8.43602731,  6.1764987 ]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [9]:
print(y)

[[0.65233105 0.41345414 0.7603125  0.11067135 0.74959253]
 [0.71625023 0.02045568 0.89715346 0.30766303 0.95675051]
 [0.4971545  0.97621689 0.58681699 0.64892518 0.44117848]]


In [10]:
np.mean(y)

0.5823284350784067

In [11]:
y.mean()

0.5823284350784067

In [12]:
np.max(y)

0.976216894066484

In [13]:
np.argmax(y) #flatten 상태가정해서 최대값이 있는 인덱스 가져옴

11

In [14]:
np.var(y), np.median(y), np.std(y)

(0.0767133341162167, 0.6489251774999453, 0.2769717207879113)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [15]:
y

array([[0.65233105, 0.41345414, 0.7603125 , 0.11067135, 0.74959253],
       [0.71625023, 0.02045568, 0.89715346, 0.30766303, 0.95675051],
       [0.4971545 , 0.97621689, 0.58681699, 0.64892518, 0.44117848]])

In [16]:
np.sum(y) #전체 합

8.7349265261761

In [19]:
#축끼리 더하기
np.sum(y,axis=0)

array([1.86573578, 1.41012672, 2.24428295, 1.06725956, 2.14752152])

In [17]:
np.cumsum(y) #누적합계

array([0.65233105, 1.06578519, 1.82609769, 1.93676904, 2.68636157,
       3.4026118 , 3.42306749, 4.32022095, 4.62788398, 5.58463449,
       6.08178899, 7.05800588, 7.64482287, 8.29374805, 8.73492653])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [18]:
np.std(np.arange(1, 5))

1.118033988749895

In [29]:
z=np.random.randn(10)
print(z)

[-1.34524129  0.59756023 -0.88922083  0.21117252 -1.90474526 -0.20630617
 -0.03126256 -0.69145088  1.28331742 -0.88766822]


In [30]:
z>0

array([False,  True, False,  True, False, False, False, False,  True,
       False])

In [31]:
np.any(z>0)

True

In [33]:
np.all(z>0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [34]:
z=np.random.randn(10)
print(z)

[ 0.99637337 -1.16644394  0.32413524 -0.31115281  0.58177593  0.80518094
 -0.45219129  1.21887612 -0.22862563 -0.12209188]


In [35]:
np.where(z>0, z,0) #조건, 참일경우, 거짓일 경우

array([0.99637337, 0.        , 0.32413524, 0.        , 0.58177593,
       0.80518094, 0.        , 1.21887612, 0.        , 0.        ])