## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.11594246 0.02494625 0.70212171 0.44381614 0.28127922]
 [0.63234285 0.1768384  0.83383104 0.07987662 0.97627734]
 [0.97387999 0.92158163 0.59688667 0.2785121  0.94589517]]


In [3]:
x+y

array([[ 0.11594246,  1.02494625,  2.70212171,  3.44381614,  4.28127922],
       [ 5.63234285,  6.1768384 ,  7.83383104,  8.07987662,  9.97627734],
       [10.97387999, 11.92158163, 12.59688667, 13.2785121 , 14.94589517]])

* Scalar(상수)와의 연산

In [4]:
x+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [6]:
x%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [15]:
a=np.arange(12).reshape(4,3)
b=np.arange(100,103)
c=np.arange(1000,1004)
d=b.reshape(1,3)

In [16]:
a+b #b stretch

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [17]:
#a+c 오류, broadcasting은 뒤에서부터 비교
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [18]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])