## 학습목표
1. boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [3]:
x=np.random.randint(1,100,size=10)
print(x)

[41  6 94 13 63 57 62 26 71 24]


In [5]:
even_mask=x%2==0 #불리언 리스트

In [6]:
print(even_mask)

[False  True  True False False False  True  True False  True]


- bool 리스트를 인덱스로 전달

In [7]:
x[even_mask]#filter 적용, true 인 값만 나옴

array([ 6, 94, 62, 26, 24])

In [8]:
x[x%2==0] #간단히도 사용 가능

array([ 6, 94, 62, 26, 24])

In [9]:
x[x>30]

array([41, 94, 63, 57, 62, 71])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [10]:
x[(x%2==0)&(x<30)]

array([ 6, 26, 24])

In [11]:
x[(x>50)|(x<30)]

array([ 6, 94, 13, 63, 57, 62, 26, 71, 24])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [13]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [15]:
len(temp[temp>25.0])
np.sum(temp>25.0)

21

In [16]:
np.mean(temp[temp>25.0])

26.857142857142858