## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x=np.random.rand(3,3)

print(x)

x@np.linalg.inv(x) #대각선 수는 1 나머지는 0
#@는 행렬의 곱 표현

[[0.85282907 0.58486952 0.90627537]
 [0.8873061  0.78127715 0.31459296]
 [0.92258895 0.01907064 0.45819752]]


array([[ 1.00000000e+00,  5.54334670e-17, -1.07502965e-16],
       [ 4.48467866e-19,  1.00000000e+00, -3.21001576e-17],
       [-4.15231347e-17, -3.63133580e-17,  1.00000000e+00]])

In [3]:
np.matmul(x,np.linalg.inv(x))

array([[ 1.00000000e+00,  5.54334670e-17, -1.07502965e-16],
       [ 4.48467866e-19,  1.00000000e+00, -3.21001576e-17],
       [-4.15231347e-17, -3.63133580e-17,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [4]:
A=np.array([[1,1],[2,4]])
B=np.array([25,64])
x=np.linalg.solve(A,B)
print(x)

[18.  7.]


In [5]:
np.allclose(A@x,B) #두개의 값이 같은가?

True